#!/usr/bin/env bun
import { existsSync, readdirSync, statSync } from 'fs';
import { join, relative, resolve } from 'path';

const SCRIPT_DIR = import.meta.dir;
const UI_DIST = resolve(SCRIPT_DIR, '..', '..', 'ui', 'dist');
const MANIFEST_PATH = resolve(SCRIPT_DIR, '..', 'src', 'embedded-ui.ts');
const IMPORT_BASE = '../../ui/dist';

function walk(dir: string): string[] {
  const entries = readdirSync(dir);
  return entries.flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

let files: string[] = [];
if (existsSync(UI_DIST)) {
  files = walk(UI_DIST)
    .map((f) => relative(UI_DIST, f).split('\\').join('/'))
    .filter((f) => !f.split('/').some((seg) => seg === '.DS_Store' || seg === 'Thumbs.db'))
    .sort();
}

const imports: string[] = [];
const entries: string[] = [];
files.forEach((f, i) => {
  const id = `f${i}`;
  imports.push(`import ${id} from '${IMPORT_BASE}/${f}' with { type: 'file' };`);
  entries.push(`  '/${f}': ${id},`);
});

const code = `// AUTO-GENERATED by scripts/generate-ui-manifest.ts. Do not edit.
${imports.join('\n')}

export const uiAssets: Record<string, string> = {
${entries.join('\n')}
};

export const indexHtmlPath: string | undefined = uiAssets['/index.html'];
`;

await Bun.write(MANIFEST_PATH, code);
console.log(`[ui-manifest] wrote ${MANIFEST_PATH} (${files.length} files)`);
